### ISSUE TITLE
remove development script from homepage

### ISSUE THREAD

**Issue by paulirish** [Modernizr/the-old-modernizr.com#14]
or hotlink some pretified build?

basically we dont want people ending up like these guys:

Modernizr/Modernizr#307

see also my last comment there.

**Comment by ryanseddon** [comment]
It should just be a link to the download page with everything checked.

**Comment by paulirish** [comment]
++

**Comment by bobthecow** [comment]
:+1: I'm with @ryanseddon ... hotlink a pre-checked download page.

**Comment by paulirish** [comment]
I think we'll need some shorthand `#omgall` trick that builderapp.js will then read and check ALL boxes. @SlexAxton hows that sound

**Comment by paulirish** [comment]
fixed.

**Comment by paulirish** [comment]
i added a `dontmin` trick to builderapp that checks the "dont minify source" box. it stays out of the computed download URL so its just quite temporary. 

unfortunately all comments are removed, though it is formatted. We might have to revisit how we show modernizr.js at master via the site later on.

**Comment by bobthecow** [comment]
@paulirish I like the idea of `#omgall` too.

**Comment by ryanseddon** [comment]
Should this include all the community detects in the builder too? And you missed Media query checkbox.

**Comment by akbargumbira** [comment]
Are flexbox legacy, html5shiv w/ printshiv, and media query intentionally not being checked when using development option to download?

**Comment by stucox** [comment]
I’d say yes to flexboxlegacy but no to printshiv, if the dev preset is intended to match [modernizr-latest.js](http://modernizr.com/downloads/modernizr-latest.js).

Although it’s unlikely the current builder will change now – it’s all being refactored/rewritten for v3 and we’re discussing what should be in the development version [over here](https://github.com/Modernizr/Modernizr/issues/1148).
